### ISSUE TITLE
Cannot find module './constants'

### ISSUE THREAD

**Issue by zewas-digital** [koljam/vendure-cron-plugin#1]
Hi there,

I added your plugin with `yarn add koljam/vendure-cron-plugin` and added 
```ts 
CronPlugin.init({
      cron: [
        {
          schedule: "*/5 * * * *",
          task: () => {
            console.log("Running task every 5 minutes");
          },
        },
      ],
      logEvents: true
    })
```

to the `vendure-confug.ts`. Now when i start my app it thrwos the error:

```
Error: Cannot find module './constants'

 requireStack: [
    '/projectPath/node_modules/vendure-cron-plugin/lib/src/plugin.js',
    '/projectPathnode_modules/vendure-cron-plugin/lib/index.js',
    '/projectPathsrc/vendure-config.ts',
    '/projectPath/src/index.ts' 
 ]
```

I tried to add a .ts on the import in your plugin.ts but the error still accurs.

Any ideas how to solve this error?

vendure/core: v2.1.5
vendure-cron-plugin: v1.0.5

**Comment by koljam** [comment]
Hey, can you confirm that there are files called constants.d.ts or constants.js in the folder `node_modules\vendure-cron-plugin\lib\src` ?
If not, try reinstalling the module.

**Comment by zewas-digital** [comment]
Hey sorry I made a mistake while I was looking at the path I looked at `plugin/src` and not in `plugn/lib/src`
in `plugin/src` there is a constants.ts
but in `plugin/lib/src` there is no `constants.js`, i reinstalled the plugin now but there is still no `constants.js` in the `plugin/lib/src` folder

**Comment by koljam** [comment]
Maybe try changing your package.json:

~"vendure-cron-plugin": "koljam/vendure-cron-plugin",~
`"vendure-cron-plugin": "^1.0.5",`

Or try reinstalling with `yarn add vendure-cron-plugin`

**Comment by zewas-digital** [comment]
That resolved it, after reinstalling with `yarn add vendure-cron-plugin` it works fine.

Thaks for your help :)
